### ISSUE TITLE
[RFE] Move to python3.7 due to asyncio changes

### ISSUE THREAD

**Issue by jan-zmeskal** [grafuls/disruption_generator#38]
Since asyncio package seen significant (and backwards-incompatible) changes, we should consider moving to python3.7 now when such move would not be expensive.

Python 3.7 asyncio changes: https://docs.python.org/3/whatsnew/3.7.html#asyncio

You can easily see how 3.7 removes a lot of boilerplate code in this example - compare solving the same task with [python3.6](https://github.com/yeraydiazdiaz/asyncio-ftwpd/blob/pre-3.7/1-sync-async-execution-asyncio-await.py) and [python3.7.](https://github.com/yeraydiazdiaz/asyncio-ftwpd/blob/master/1-sync-async-execution.py)

**Comment by grafuls** [comment]
We are not affected by the BC issues:
async and await names are now reserved keywords. Code using these names as identifiers will now raise a SyntaxError.
Eventually moving to 3.7 wouldn't imply a massive change hence might not be worthy bothering and restricting users to have 3.7 installed.
